version: '3'
services:
  web:
    container_name: simpleannotationserver_solr_1 
    build: 
        context: .
        dockerfile: docker/sas-solr/Dockerfile
    ports:
      - "8888:8080"
  solr:
    container_name: sas_solr
    image: "solr:8"
    ports:
      - "8983:8983" 
    volumes:
      - "./src/main/resources/solr:/tmp/config:ro"
      - "./solr-data:/var/solr/data"
    entrypoint:
      - bash
      - "-c"
      - "solr-precreate testannotations /tmp/config; solr-precreate annotations /tmp/config; exec solr -f"
