version: '3'
services:
  web:
    container_name: simpleannotationserver_solr_1 
    build: 
        context: .
        dockerfile: docker/sas-solr/Dockerfile
    ports:
      - "8888:8080"
  solr:
    container_name: sas_solr
    image: "solr:latest"
    ports:
      - "8983:8983" 
    volumes:
      - "./src/main/resources/solr:/tmp/config:ro"
      - "./home:/var/solr"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core testannotations /tmp/config; precreate-core annotations /tmp/config; exec solr -f"
