name: Elastic

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Starting ElasticSearch
        run: docker-compose -f docker/sas-elastic/docker-compose.yml --project-directory . up -d elastic
      - name: Wait for Elastic to start
        run: .github/bin/waitHttp.sh "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"
      - name: Run Tests
        run: export "config=elastic.properties" && mvn test
        
